language: objective-c
osx_image: xcode7.1
branches:
  only:
    - master
before_install:
  - gem install xcpretty
script:
  - set -o pipefail
  - xcodebuild -project Example/DynamicColorExample.xcodeproj -scheme iOSTests -sdk iphonesimulator -destination "id=74B65E5F-38DA-42D9-AD99-1DF06695DC54" -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
  - xcodebuild -project Example/DynamicColorExample.xcodeproj -scheme OSXTests -sdk macosx -configuration Release ONLY_ACTIVE_ARCH=YES test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
